#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#Start with 1 and 2. By concidering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

next = 0
current_1 = 1
current_2 = 2
final = 2

#0, 1, 2, 3, 5, 8, 13
#current_1 + current_2 = next
#0 + 1 = 1
#1 + 1 = 2
#1 + 2 = 3
#2 + 3 = 5
#3 + 5 = 8
#5 + 8 = 13
print(current_1)
print(current_2)

while next < 4000000:
    next = current_1 + current_2
    current_1 = current_2
    current_2 = next
    
    if next % 2 == 0:
        final += next
    print(next)

print("\nFinal count")
print(final)